name: Píratar í Borgarbyggð
favicon: null
layout_spectrum: 0.92328
typography_spectrum: 0.48305
title: Píratar í Borgarbyggð
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#563480'
    - '#fefefe'
    - '#201720'
    - '#60546e'
    - '#9b92a5'
  brandStrength: 0.625
  lightness: 0.4823390149977058
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
